version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/whchat
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
