# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo "Starting build process..."
#   build:
#     commands:
#       - echo "Building the project..."
#   post_build:
#     commands:
#       - echo "Build completed on `date`"

# artifacts:
#   files:
#     - '**/*'
#   discard-paths: yes

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build..."
  build:
    commands:
      - echo "Running build..."
  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - appspec.yml
    - requirements.txt
    - '**/*'
  discard-paths: no