version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Building the project..."
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  discard-paths: yes
